name: flutter-ci
on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Flutter version
        run: flutter --version

      - name: Get packages
        run: flutter pub get

      - name: Lint
        run: flutter analyze

